[package]
name = "circini-derive"
version = "0.0.1"
authors = ["Davi Silva <blueridanus@gmail.com>"]

[dependencies]
quote = "0.6"

[dependencies.syn]
version = "0.15"
features = ["full"]

[lib]
proc-macro = true